services:
  db:
    image: postgres:latest
    ports:
      - "5431:5431"
    restart: always
    environment:
      POSTGRES_PASSWORD: max123

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"